import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs-extra';
import { requiredSpecs, optionalSpecs } from './specs.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TEMPLATES_DIR = path.join(__dirname, '..', 'templates', 'spac');

export async function initProject(projectName, selectedOptionalFiles, preset) {
  const projectDir = path.resolve(process.cwd(), projectName);
  const spacDir = path.join(projectDir, 'spac');

  await fs.ensureDir(spacDir);

  const today = new Date().toISOString().split('T')[0];
  const hints = preset ? preset.hints : {};

  // Copy required specs
  for (const spec of requiredSpecs) {
    await copyTemplate(spec.file, spacDir, projectName, today, hints);
  }

  // Copy selected optional specs
  const optionalFiles = selectedOptionalFiles || optionalSpecs.map((s) => s.file);
  for (const file of optionalFiles) {
    await copyTemplate(file, spacDir, projectName, today, hints);
  }

  // Generate 00-SCOPE-OF-WORK.md
  const allSpecFiles = [
    ...requiredSpecs.map((s) => s.file),
    ...optionalFiles,
  ];
  await generateScopeOfWork(spacDir, projectName, preset, allSpecFiles);

  return { projectDir, spacDir };
}

async function copyTemplate(fileName, destDir, projectName, date, hints) {
  const srcPath = path.join(TEMPLATES_DIR, fileName);
  const destPath = path.join(destDir, fileName);

  let content = await fs.readFile(srcPath, 'utf-8');
  content = content.replaceAll('{{PROJECT_NAME}}', projectName);
  content = content.replaceAll('{{DATE}}', date);

  // Replace preset hints
  for (const [key, value] of Object.entries(hints)) {
    content = content.replaceAll(`{{${key}}}`, value);
  }

  // Clear any remaining unreplaced hint placeholders
  content = content.replace(/\{\{[A-Z_]+_HINT\}\}/g, '<!-- TODO -->');

  await fs.writeFile(destPath, content, 'utf-8');
}

async function generateScopeOfWork(spacDir, projectName, preset, specFiles) {
  const specList = specFiles.map((f) => `| \`${f}\` | |`).join('\n');
  const presetLabel = preset ? preset.name : 'General';
  const today = new Date().toISOString().split('T')[0];

  const content = `# 📑 ${projectName} — Scope of Work (SOW)

## Project Type: ${presetLabel}
## Date: ${today}
## Prepared by: Pi R Square Co., LTD

---

# 1. Project Overview

<!-- TODO: Describe the project in 2-3 sentences -->

---

# 2. Specification Documents

All project specifications are in this folder. Read them in order before starting any work.

### Reading Order

| Order | File | Purpose |
|-------|------|---------|
| 1 | \`01-PRD.md\` | Understand what this project is, its goals and scope |
| 2 | \`02-TECH-STACK.md\` | Technologies used — must follow this stack |
| 3 | \`03-DATABASE-SCHEMA.md\` | Database structure, tables, relations |
| 4 | \`04-PROJECT-STRUCTURE.md\` | Folder and file organization |

### All Spec Files

| File | Status |
|------|--------|
${specList}

---

# 3. Constraints & Rules

- **Follow the tech stack** defined in \`02-TECH-STACK.md\` — do not change without approval
- **Follow the database schema** defined in \`03-DATABASE-SCHEMA.md\` — do not modify without approval
- **Create files and folders** according to \`04-PROJECT-STRUCTURE.md\`
- **Update relevant spec files** whenever significant changes are made

---

# 4. How to Use with AI Tools

| AI Tool | How to Use |
|---------|-----------|
| **Claude Code** | Copy this file's content into \`CLAUDE.md\` at the project root |
| **ChatGPT** | Paste all spec files as context before giving instructions |
| **Cursor / AI IDE** | Add \`spac/\` folder as context files in settings |
| **Other AI** | Send this file along with relevant spec files as reference |

---

*Generated by [@pirsquare/spac-kit](https://github.com/Pi-R-SQUARE-Co-ltd/spac-kit) — Spec-Driven Development by Pi R Square Co., LTD*
`;

  await fs.writeFile(path.join(spacDir, '00-SCOPE-OF-WORK.md'), content, 'utf-8');
}
